import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import { History } from "../components/History";
import { UserInput } from "../components/UserInput";

const ChatRoom: React.FC<Props> = ({}) => {
  const [chatHistory, setChatHistory] = useState<string[]>([]);

  return (
    <>
      <History chatHistory={chatHistory} />
      <UserInput chatHistory={chatHistory} setChatHistory={setChatHistory} />
    </>
  );
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Chat with a bot</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ChatRoom />
      </main>
    </>
  );
}
